language: cpp
compiler: gcc
os: centos

#cache:
#  directories:
#  - node_modules
install:
- yum install thrift-devel
- yum install protobuf-devel
- yum install libevent-devel
- yum install log4cpp-devel
- yum install json-cpp-devel
- yum install libcurl-devel
- yum install gflags-devel
- yum install glog-devel
- yum install hiredis-devel
- yum install sqlilte-devel



script:
- build.sh

#after_success:
#- hexo deploy